### PR TITLE
Humanize 4.0.0 drops support for EOL Python 3.6

### PR DESCRIPTION
**Pull request by hugovk**
https://github.com/jmoiron/humanize/releases/tag/4.0.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by conda-grayskull** [comment]
================ **HOST** ================
Requirements for **host**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python >=3.7 | python | :heavy_exclamation_mark: |
| pip | pip | :heavy_check_mark: |
| setuptools_scm |  | :x: |


================ **RUN** ================
Requirements for **run**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python >=3.7 | python | :heavy_exclamation_mark: |

**Comment by ocefpaf** [comment]
Thanks @hugovk! I removed automerge to prevent something like this from happening again. We should be able to re-add it once we start using grayskull to check the dependencies.

**Comment by hugovk** [comment]
You're welcome, sounds good!

For reference, I'm not planning on dropping Python 3.7 until it's EOL on 2023-06-27 so that gives some time :)

**Comment by ocefpaf** [comment]
BTW, just to give @marcelotrevisani a data point, grayskull doesn't parse packages that use pyproject.toml packages yet. We need to fix that as the number of packages using this standard is growing.

**Pull request merged**
